#!/bin/bash
# =============================================================================
# NGO OpsBot — one-command dev environment setup
# Usage: bash scripts/setup_dev.sh
#
# What it does:
#   1. Verifies Python 3.12 is available
#   2. Creates a virtual environment at .venv (if absent)
#   3. Installs the project with dev extras
#   4. Installs pre-commit hooks
#   5. Creates .env from .env.example (if absent) and injects ENCRYPTION_KEY
#   6. Starts postgres + redis via docker compose
#   7. Waits for postgres to be healthy
#   8. Runs alembic migrations
#   9. Installs dashboard npm dependencies
#
# Make this script executable:
#   chmod +x scripts/setup_dev.sh
# =============================================================================
set -euo pipefail

# Colours
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

info()    { echo -e "${CYAN}[setup]${NC} $*"; }
success() { echo -e "${GREEN}[setup]${NC} $*"; }
warn()    { echo -e "${YELLOW}[setup]${NC} $*"; }
error()   { echo -e "${RED}[setup]${NC} $*" >&2; exit 1; }

# Resolve the project root regardless of where the script is called from
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

info "Setting up NGO OpsBot dev environment..."
info "Project root: ${PROJECT_ROOT}"
cd "${PROJECT_ROOT}"

# ---------------------------------------------------------------------------
# 1. Check Python 3.12
# ---------------------------------------------------------------------------
info "Checking Python version..."
PYTHON_BIN=""
for cmd in python3.12 python3 python; do
    if command -v "$cmd" &>/dev/null; then
        version=$("$cmd" --version 2>&1 | awk '{print $2}')
        major=$(echo "$version" | cut -d. -f1)
        minor=$(echo "$version" | cut -d. -f2)
        if [[ "$major" == "3" && "$minor" -ge 12 ]]; then
            PYTHON_BIN="$cmd"
            success "Found Python ${version} at $(command -v "$cmd")"
            break
        fi
    fi
done

if [[ -z "$PYTHON_BIN" ]]; then
    error "Python 3.12+ is required but was not found. Install it via pyenv, homebrew, or python.org."
fi

# ---------------------------------------------------------------------------
# 2. Create virtual environment
# ---------------------------------------------------------------------------
VENV_DIR="${PROJECT_ROOT}/.venv"
if [[ ! -d "$VENV_DIR" ]]; then
    info "Creating virtual environment at .venv..."
    "$PYTHON_BIN" -m venv "$VENV_DIR"
    success "Virtual environment created."
else
    info "Virtual environment already exists at .venv — skipping creation."
fi

# Activate
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
success "Virtual environment activated."

# ---------------------------------------------------------------------------
# 3. Install Python dependencies
# ---------------------------------------------------------------------------
info "Installing Python dependencies (pip install -e '.[dev]')..."
pip install --upgrade pip --quiet
pip install -e ".[dev]" --quiet
success "Python dependencies installed."

# ---------------------------------------------------------------------------
# 4. Pre-commit hooks
# ---------------------------------------------------------------------------
info "Installing pre-commit hooks..."
pre-commit install
success "Pre-commit hooks installed."

# ---------------------------------------------------------------------------
# 5. .env file
# ---------------------------------------------------------------------------
ENV_FILE="${PROJECT_ROOT}/.env"
ENV_EXAMPLE="${PROJECT_ROOT}/.env.example"

if [[ ! -f "$ENV_FILE" ]]; then
    if [[ -f "$ENV_EXAMPLE" ]]; then
        info "Copying .env.example to .env..."
        cp "$ENV_EXAMPLE" "$ENV_FILE"
    else
        warn ".env.example not found — creating a minimal .env from scratch."
        cat > "$ENV_FILE" <<'ENVEOF'
# Auto-generated by setup_dev.sh — fill in real values as needed
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/ngoopsbot
SYNC_DATABASE_URL=postgresql+psycopg2://postgres:postgres@localhost:5432/ngoopsbot
REDIS_URL=redis://localhost:6379/0
SECRET_KEY=dev-secret-key-change-in-production
ENCRYPTION_KEY=
ADMIN_API_KEY=dev-admin-key
WEBHOOK_SECRET=dev-webhook-secret
APP_BASE_URL=http://localhost:8000
ENV=development
DEBUG=true
LOG_LEVEL=DEBUG
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
SENDGRID_API_KEY=
SENDGRID_FROM_EMAIL=noreply@example.com
MSG91_API_KEY=
MSG91_SENDER_ID=NGOBOT
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
SENTRY_DSN=
ENVEOF
    fi
    success ".env file created."
else
    info ".env already exists — skipping copy."
fi

# Generate ENCRYPTION_KEY if not already set
if grep -q '^ENCRYPTION_KEY=$' "$ENV_FILE" || ! grep -q '^ENCRYPTION_KEY=' "$ENV_FILE"; then
    info "Generating ENCRYPTION_KEY (Fernet)..."
    ENC_KEY=$("$PYTHON_BIN" -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    # Replace the empty ENCRYPTION_KEY line (or append if missing)
    if grep -q '^ENCRYPTION_KEY=' "$ENV_FILE"; then
        sed -i.bak "s|^ENCRYPTION_KEY=.*|ENCRYPTION_KEY=${ENC_KEY}|" "$ENV_FILE" && rm -f "${ENV_FILE}.bak"
    else
        echo "ENCRYPTION_KEY=${ENC_KEY}" >> "$ENV_FILE"
    fi
    success "ENCRYPTION_KEY generated and written to .env."
else
    info "ENCRYPTION_KEY already set — skipping generation."
fi

# ---------------------------------------------------------------------------
# 6. Start Docker services (postgres + redis only)
# ---------------------------------------------------------------------------
if ! command -v docker &>/dev/null; then
    warn "Docker not found — skipping service startup. Start postgres and redis manually."
else
    info "Starting postgres and redis via docker compose..."
    docker compose up -d postgres redis
    success "Docker services started."
fi

# ---------------------------------------------------------------------------
# 7. Wait for postgres to be ready
# ---------------------------------------------------------------------------
info "Waiting for postgres to be ready..."
MAX_TRIES=30
TRIES=0
until docker compose exec -T postgres pg_isready -U postgres -d ngoopsbot &>/dev/null; do
    TRIES=$((TRIES + 1))
    if [[ "$TRIES" -ge "$MAX_TRIES" ]]; then
        error "Postgres did not become ready after ${MAX_TRIES} attempts. Check: docker compose logs postgres"
    fi
    echo -n "."
    sleep 1
done
echo ""
success "Postgres is ready."

# ---------------------------------------------------------------------------
# 8. Run Alembic migrations
# ---------------------------------------------------------------------------
info "Running database migrations (alembic upgrade head)..."
# Export DATABASE_URL so alembic can find it without loading the full app config
export DATABASE_URL
DATABASE_URL=$(grep '^SYNC_DATABASE_URL=' "$ENV_FILE" | cut -d= -f2- || true)
if [[ -z "$DATABASE_URL" ]]; then
    DATABASE_URL="postgresql+psycopg2://postgres:postgres@localhost:5432/ngoopsbot"
fi
# Use asyncpg url from .env for alembic (it handles both sync/async)
alembic upgrade head
success "Migrations applied."

# ---------------------------------------------------------------------------
# 9. Dashboard setup
# ---------------------------------------------------------------------------
DASHBOARD_DIR="${PROJECT_ROOT}/dashboard"
if [[ -d "$DASHBOARD_DIR" ]]; then
    info "Setting up Next.js dashboard..."
    cd "$DASHBOARD_DIR"

    info "Running npm ci..."
    npm ci --silent

    DASHBOARD_ENV="${DASHBOARD_DIR}/.env.local"
    DASHBOARD_ENV_EXAMPLE="${DASHBOARD_DIR}/.env.local.example"
    if [[ ! -f "$DASHBOARD_ENV" ]]; then
        if [[ -f "$DASHBOARD_ENV_EXAMPLE" ]]; then
            cp "$DASHBOARD_ENV_EXAMPLE" "$DASHBOARD_ENV"
            success "Copied dashboard/.env.local.example to dashboard/.env.local"
        else
            warn "dashboard/.env.local.example not found — creating minimal dashboard .env.local"
            cat > "$DASHBOARD_ENV" <<'DASHENVEOF'
# Auto-generated by setup_dev.sh
NEXT_PUBLIC_API_URL=http://localhost:8000
DASHENVEOF
        fi
    else
        info "dashboard/.env.local already exists — skipping."
    fi

    cd "${PROJECT_ROOT}"
    success "Dashboard setup complete."
else
    warn "dashboard/ directory not found — skipping dashboard setup."
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo ""
success "=============================================="
success " NGO OpsBot dev environment is ready!"
success "=============================================="
echo ""
echo "  Start API server:     uvicorn app.main:app --reload"
echo "  Start dashboard:      cd dashboard && npm run dev"
echo "  Run tests:            make test"
echo "  Seed database:        make seed"
echo ""
