"""
Shared SQLAlchemy declarative base and common column mixins.

Design notes
------------
* ``Base`` is a plain ``DeclarativeBase`` with no shared columns — each model
  opts in to ``UUIDMixin`` and/or ``TimestampMixin`` explicitly, which keeps
  audit-only tables (AuditLog, ReminderLog) free of unnecessary columns.
* ``TimestampMixin`` uses ``server_default=func.now()`` so the DB is the
  single source of truth for wall-clock values across all replicas.
* ``onupdate`` for ``updated_at`` calls ``func.now()`` (a SQLAlchemy
  ``Function`` expression) so it works correctly via both Python ORM updates
  and bulk UPDATE statements.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Project-wide declarative base — no shared columns."""
    pass


class UUIDMixin:
    """UUID v4 primary key, generated by the application layer."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """Server-managed ``created_at`` / ``updated_at`` audit columns."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
